CREATE VOLATILE MULTISET TABLE USER_LOGIN.ML_FINANCIAL_BILLS_MOB AS (
SELECT
IDNT_COMP_FACT,
ppdd_date,
Row_Number() Over (PARTITION BY IDNT_COMP_FACT ORDER BY ppdd_date ASC) AS rk,
Abs(Sum(TOTAL_PAID)) AS GAINS,
Abs(Sum(BALANCE_DUE)) AS PERTES,
(GAINS - PERTES) AS RISQUE
FROM DB_DATALAB_DAF.ML_FINANCIAL_RISK T1
INNER JOIN VH_B_FINANCE.TDI_ARBOR_SOLDE_FACTURE T2
ON T1.IDNT_COMP_FACT = T2.IDNT_ACCS
GROUP BY 1, 2
QUALIFY rk < NB_FACTURES
) WITH DATA UNIQUE PRIMARY INDEX (IDNT_COMP_FACT, bill_ref_no);