UPDATE T1
FROM DB_DATALAB_DAF.ML_FINANCIAL_RISK T1, (SELECT *
FROM db_datalab_daf.PERM_985_04_FIN 
QUALIFY Count(*) Over (PARTITION BY ORDER_PACKAGE_NUMBER) = 1) T2
SET IDNT_COMP_FACT = T2.IDNT_COMP_FACT
WHERE 1=1
AND T1.ORDER_PACKAGE_NUMBER = T2.ORDER_PACKAGE_NUMBER;